<div style="width:1000px;">
<h1>Card Order List</h1>
<ul class="tabs fullTabs">
    <li><a href="#tabOrder" tableIndex="0">Requests</a></li>
    <li><a href="#tabHistory" tableIndex="1">History</a></li>
</ul>
<div class="tab_container">
    <div id="tabOrder" class="tab_content nopadding">
        <table class="dataTable">
            <thead>
                <tr>
                    <th width="40">Order No.</th>
                    <th width="80">Requesting Branch</th>
                    <th width="80">Date/Time Requested</th>
                    <th width="60">Card Type</th>
                    <th width="30">Req. Qty.</th>
                    <th width="30">Card BIN</th>
                    <th width="70">Status</th>
                    <th width="80">Card Detail</th>
                    <th>personalized</th>
                    <th>embossname</th>
                    <th>brseqno</th>
                    <?php echo html_entity_decode($p1); ?>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
	</div>
    <div id="tabHistory" class="tab_content nopadding">
    	<table class="dataTable">
        	<thead>
                <tr>
                	<th>Order No.</th>
                    <th>Requesting Branch</th>
                    <!--<th>Branch</th>-->
                    <th>Date/Time Requested</th>
                    <th>Date/Time Generated</th>
                    <th>Card Type</th
                    ><th>Req. Qty.</th>
                    <th>Gen. Qty.</th>
                    <th>Card BIN</th>
                    <th>Generated By</th>
                    <th>Status</th>
                    <th>Card Detail</th>
                    <?php echo html_entity_decode($p1); ?>
                </tr>
			</thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<div id="bottom">
    <span class="buttons floatLeft">
        <button id="newBtn">New Batch Order</button
        ><button id="reqBtn">Personalized Request</button
        ><?php echo html_entity_decode($batchUploadBtn); ?><button id="modifyBtn">Modify</button
        ><button id="removeBtn">Remove</button
        ><button id="cancelBtn" value="card/orderrequest/cancel">Cancel Order</button>
    </span>
    <span class="buttons floatRight">
        <button id="refreshBtn">Refresh</button
        ><button class="closebtn">Close</button>
    </span>
</div>
<div id="customToolbar" class="hidden">
    <div class="top">
        <!--<div class="dataTables_custom floatLeft"><span class="info"></span></div>-->
        <div class="dataTables_custom floatLeft" style="padding:0 !important">
        	<span class="info">
        		Branch:
                <select class="branchList" style="width:150px">
                	<option value="-1">ALL</option>
					<?php echo html_entity_decode($branches); ?>
                </select>
			</span>
		</div>
    </div>
</div>
<style>
.dataTables_scrollBody{height:220px !important;max-height:220px !important;}
.dataTables_filter input {
	width: 150px;
}
</style>
<script>
$(function () {
    var newBtn = '#newBtn',
        reqBtn = '#reqBtn',
        batchBtn = '#batchUploadBtn',
        refreshBtn = '#refreshBtn',
		modifyBtn = '#modifyBtn',
		removeBtn = '#removeBtn',
		cancelBtn = '#cancelBtn',
		orderNo = '#orderNo',
		cardBIN = '#cardBIN',
		reqQty  = '#reqQty',
		cardType = '#cardType',
		card = {},
        form = $('form');
	
	initSession('<?php echo $sessionExp; ?>');
    //$(DATATABLE).find('tbody tr').die('dblclick');
	var buttons = modifyBtn + ',' + removeBtn + ',' + cancelBtn;
	
    oTable = $(DATATABLE).dataTable({
        bRetrieve: true,
        bJQueryUI: true,
		aLengthMenu: DTLENGTHMENU,
		aoColumns: ([ //hide columns   
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			{ bVisible: false }
			<?php echo $p2; ?>
		]),
        aaSorting: [
            [0, 'desc']
        ],
        sScrollY: '100%',
        sScrollX: '100%',
        sPaginationType: 'full_numbers',
        fnInitComplete: function () {
			$(buttons).attr('disabled', true);
            $.fn.dataTableExt.iApiIndex = 0;
			this.fnSetColumnVis(8, false);
			this.fnSetColumnVis(9, false);
        },
        fnRowCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
			var i = parseInt($(TABS + '.active').find('a').attr('tableIndex'));
			
			switch (i) {
				case 0:
					$('td:eq(0), td:eq(3), td:eq(4)', nRow).attr('align', 'center');
					
					$(nRow).attr('id', aData[0]).unbind('click dblclick').click(function() {		
						//set temp var
						card = {
							orderNo: aData[0],
							cardBIN: aData[5],
							reqQty: aData[4],
							cardType: aData[2],
							customer: aData[7],
							isPersonalized: aData[8],
							embossName: aData[9],
							brseqno: aData[10]
							<?php echo $p3; ?>
						}
							
						//highlight rows
						$('tbody tr').removeClass('rowSelected');
						$(this).addClass('rowSelected');
						
						$(buttons).removeAttr('disabled');
					}).dblclick(function () {
						$(modifyBtn).trigger('click');
					});
					
					$('tbody tr').removeClass('rowSelected');
					$(buttons).attr('disabled', true);
					
					card = {};					
					break;
				case 1:
					//red row
					if (aData[9] === 'CANCELLED') {
						$(nRow).addClass('redRow');
					}
					$('td:eq(0), td:eq(5), td:eq(6), td:eq(7)', nRow).attr('align', 'center');
					
					$(nRow).attr('id', aData[0]).unbind('click');
					break;
			}
            return nRow;
        }
    });
	getData(0);
	//default Action
	$(TABCONTENT).hide(); //hide all content
	$(TABS).first().addClass('active').show(); //activate first tab
	$(TABCONTENT).first().show(); //show first tab content
	<?php echo $uiToolbar; ?>  			
	//onClick Event
	$(TABS).click(function() {
		if (!$(this).hasClass('active')) {
			form.validationEngine('hideAll');
			$(TABS).removeClass('active'); //remove any "active" class
			$(this).addClass('active'); //add "active" class to selected tab
			$(TABCONTENT).hide(); //hide all tab content
			
			var $activeTab = $(this).find('a').attr('href'); //find the rel attribute value to identify the active tab + content
			$($activeTab).show();
			
			$(WRAPPER).height('auto');
			
			var tblIndex = $(this).find('a').attr('tableIndex');
			switch (parseInt(tblIndex)) {
				case 0:
					/*$.fn.dataTableExt.iApiIndex = tblIndex;
					oTable.fnSetColumnVis(7, false);*/
					$(buttons).show();					
					break;
				case 1:
					//$.fn.dataTableExt.iApiIndex = tblIndex;
					$(buttons).hide();
					break;
				default:
					break;
			}
			getData(tblIndex);
		}
		return false;
	});

	
	$('.branchList').change(function () {
		var index = $(TABS + '.active').find('a').attr('tableIndex');
		getData(index);
	});
	
	$(DATATABLE).find('tbody tr').live('dblclick', function() {
		//if record count > 0
		if (oTable.fnSettings().fnRecordsDisplay() > 0) {
			$(i).trigger('click');
		}
	});
	
    $(newBtn).click(function () {
        window.location.hash = 'card/batchorder';
        return false;
    });
	
    $(reqBtn).click(function () {
        window.location.hash = 'customer/search/cardrequest';
        return false;
    });
	
	$(batchBtn).click(function () {
        window.location.hash = 'card/batchupload';
        return false;
    });

    $(refreshBtn).click(function (e) {
		var index = $(TABS + '.active').find('a').attr('tableIndex');
		getData(index);
        e.preventDefault();
    });
	
	$(modifyBtn).click(function (e) {
		if (card) {
			$.ajax({
				type: 'POST',
				url: 'card/orderrequest/cache',
				data: card,
				dataType: 'json',
				success: function(data) {
					if (data.success === true) {
						window.location.hash = data['page'];
					}
				}
			});
		} else {
			messageBox('Please select an item from the list');
		}
		e.preventDefault();
    });
	
	$(removeBtn).click(function (e) {
		if (card) {
            messageBox('Remove Card Order <strong>['+ card.orderNo +']</strong>?','Confirm','confirm',function() {
				//serialize AJAX request
				requests.push(
					$.ajax({
						type: 'POST',
						url: 'card/orderrequest/remove',
						data: {
							orderNo: card.orderNo
						},
						dataType: 'json',
						beforeSend: function() {
							waitMessage('Removing Card Order <strong>['+ card.orderNo +']</strong>');
						},
						success: function(data) {
							if (data.success === true) {
								messageBox(data.message);
								oTable.fnDeleteRow(oTable.fnGetPosition($('#' + card.orderNo)[0]));
							}
						}
					})
				);
            })
        } else {
            messageBox('Please select an item from the list')
        }
        e.preventDefault();
    });
	
	$(cancelBtn).click(function (e) {
		if (card) {
            messageBox('Cancel Card Order <strong>['+ card.orderNo +']</strong>?','Confirm','confirm',function() {
				//serialize AJAX request
				requests.push(
					$.ajax({
						type: 'POST',
						url: 'card/orderrequest/cancel',
						data: {
							orderNo: card.orderNo
						},
						dataType: 'json',
						beforeSend: function() {
							waitMessage('Cancelling Card Order <strong>['+ card.orderNo +']</strong>');
						},
						success: function(data) {
							if (data.success === true) {
								messageBox(data.message);
								oTable.fnDeleteRow(oTable.fnGetPosition($('#' + card.orderNo)[0]));
							}
						}
					})
				);
            })
        } else {
            messageBox('Please select an item from the list')
        }
        e.preventDefault();
    });


	$(removeBtn).hide();
	//$(reqBtn).hide();
});
function getData(index)
{
	switch (index) {
		case '0':
			type = 'getOrders';
			waitMsg = 'Retrieving card order list...';
			break;
		case '1':
			type = 'getHistory';
			waitMsg = 'Retrieving card history list...';
			break;
		default:
			type = 'getOrders';
			waitMsg = 'Retrieving card order list...';
			break;
	}
	
	requests.push(
		$.ajax({
			url: 'card/orderrequest/' + type,
			type: 'GET',
			dataType: 'json',
			data: {
				brseqno: $('.branchList:eq('+ index +')').val()
			},
			beforeSend: function () {
				abortAJAXRequests();
				$.fn.dataTableExt.iApiIndex = index;
				waitMessage(waitMsg);
			},
			error: function () {
	
			},
			success: function (data) {
				if (data.success) {
					oTable.fnClearTable(0);
					oTable.fnAddData(data.aaData);
					oTable.fnDraw();
					oTable.fnAdjustColumnSizing();
				}
			},
			complete: function () {
				$(MSGBOX).dialog('close');
			}
		})
	)
}
</script>